"""add publications.updated_at

Revision ID: 9c1b8b468d58
Revises: ea69aef92deb
Create Date: 2026-09-11 12:43:55.977087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1b8b468d58'
down_revision: Union[str, Sequence[str], None] = 'ea69aef92deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Adjusted from the raw autogenerate: a plain NOT NULL ADD COLUMN fails against any
    # existing rows (nothing to backfill them with). server_default backfills existing
    # rows to "now" at migration time; dropped right after since the model sets
    # updated_at itself (default=/onupdate=) — this isn't meant to be a DB-level default
    # going forward, only a one-time backfill value.
    op.add_column('publications', sa.Column(
        'updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'),
    ))
    op.alter_column('publications', 'updated_at', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'updated_at')
    # ### end Alembic commands ###
