"""add publications table

Revision ID: ea69aef92deb
Revises: 41c7f1688bde
Create Date: 2026-09-11 11:53:21.041683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea69aef92deb'
down_revision: Union[str, Sequence[str], None] = '41c7f1688bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('social_account_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_status'), 'publications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_status'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
